/* eslint-disable */
(function (n, t) {
  onload = function () {
    _G.BPT = new Date();
    !_w.sb_ppCPL && t && sb_st(function () {
      t(new Date());
    }, 0);
  }
    ;
}
)(_w.onload, _w.si_PP);
//_w.rms.js(
 // { 'A:rms:answers:Shared:BingCore.Bundle': '/rp/-EZ3_E7ynAvG4WDjTxZ9rUpEwcA.br.js' },
  //// { 'A:rms:answers:Web:FreeSydneyHelper': '/rp/1rUTIFRcUHTZUBaDs_0q8KvUlR0.br.js' },
  //// { 'A:rms:answers:Web:SydneyFSCHelper': '/rp/itRGLeQn1eo9Z_0Z9OEGDmYnnkc.br.js' },
//  { 'A:rms:answers:VisualSystem:ConversationScope': '/rp/evAU7lx8mebBaN9xocvZx8NVZhE.br.js' },
//  { 'A:rms:answers:CodexBundle:cib-bundle': '/rp/cyU_OCO3RbZ2qeKuF-N208x6HCE.br.js' },
//  { 'A:rms:answers:SharedStaticAssets:speech-sdk': '/rp/5RUBu5dEYIDzWQtuZRVAHjBjuyc.br.js' },
//  { 'A:rms:answers:Web:SydneyWelcomeScreenBase':'/rp/J1Qt_5kw_tmsXwaKeAFz2xPNi4s.br.js' },
// // { 'A:rms:answers:Web:SydneyWelcomeScreen':'/rp/sNzL8vfHHNmyqYOSQey9fNYd3kI.br.js' },
//  { 'A:rms:answers:Web:SydneyFullScreenConv': '/rp/0UCEcxL4L_MIx61KSqZ5vt5H4V0.br.js' },
//  { 'A:rms:answers:Web:ChatHomeScreenBase': '/rp/-rTLoTob7E0ltIUEW9nZQHmVMYk.br.js' },
//  { 'A:rms:answers:Web:ChatHomeScreen': '/rp/iKLEB3hIDCT4236vCJrv0iHxANU.br.js' },
//);

_w.rms.js(
//{'A:0':0},
{'A:rms:answers:GlobalsScript:RefreshPageLongInactive':'https://r.bing.com/rp/eeSRHmOwBCiYGkxCHmb9VbJ2hT8.br.js'},
{'A:rms:answers:Shared:BingCore.Bundle':'https://r.bing.com/rp/-EZ3_E7ynAvG4WDjTxZ9rUpEwcA.br.js'},
{'A:rms:answers:VisualSystem:QuickSearch':'https://r.bing.com/rp/U6ozRLRanAQTt22qZDWCWxYnh5g.br.js'},
//{'A:1':1},
{'A:rms:answers:BoxModel:Framework':'https://r.bing.com/rp/HndC9IrfiOmnQLZpq0bxaPUIDII.br.js'},
{'A:rms:answers:SharedStaticAssets:WebVitals':'https://r.bing.com/rp/KLrSbzDKMog0mCiPcB9iwoEvlE4.br.js'},
{'A:rms:answers:WebVitals:WebVitalsMetrics4':'https://r.bing.com/rp/TaNyfCzxqBX9l7QZbgZUegopTuI.br.js'},
//{'A:2':2},
{'A:rms:answers:Shared:mlibCssClassAfterOnLoad':'https://r.bing.com/rp/cfKt7bw67nxWZkkgOIRReDE3rQI.br.js'},
//{'A:3':3},
{'A:rms:answers:Web:ClearSearchBox':'https://r.bing.com/rp/K3hC1_cQXGFr6cxRJVWYpzZJaAM.br.js'},
{'A:rms:answers:HomepageVNext:PreactLibrary':'https://r.bing.com/rp/n23ANye7L3wtUcgKxoGHb7_ezc4.br.js'},
{'A:rms:answers:HomepageVNext:SpeechSDKClone':'https://r.bing.com/rp/DmYomXZ0p9--syG1mm6CnQwvRHg.br.js'},
{'A:rms:answers:HomepageVNext:PostloadedSpeechPreactBundle':'https://r.bing.com/rp/2VYJBWEs9lbV3Q50EXL7TNnGBog.br.js'},
//{'A:4':4},
{'A:rms:answers:MultimediaComponents:SearchByImageComponentLoader':'https://r.bing.com/rp/lLk8XmbdNzzlnPRzVzDhaF9yjqw.br.js'},
{'A:rms:answers:Identity:BlueIdentityDropdownBootStrap':'https://r.bing.com/rp/Gyuq2bqitqDJM0BeAkbKXGlQXNw.br.js'},
{'A:rms:answers:Identity:BlueIdentityHeader':'https://r.bing.com/rp/n21aGRCN5EKHB3qObygw029dyNU.br.js'},
//{'A:5':5},
{'A:rms:answers:Identity:SnrWindowsLiveConnectBootstrap':'https://r.bing.com/rp/8CgcSSLayxEVUBf0swP_bQGMId8.br.js'},
{'A:rms:answers:OrgId:SsoFrame':'https://r.bing.com/rp/V_fBQ_iVmAgE_Ta_T-6BNXc0ZY4.br.js'},
{'A:rms:answers:BingAtWork:SsoContent':'https://r.bing.com/rp/9xGNA8UskvA9WHF58zbLOHZ5HvI.br.js'},
//{'A:6':6},
{'A:rms:answers:Identity:ProfilePicturePostLoader':'https://r.bing.com/rp/_2I169N92jVtSc_VEsV0nma5sRY.br.js'},
{'A:rms:answers:Identity:AccountLinkLoadProfileIcon':'https://r.bing.com/rp/gKwIRAF4fg7noG1zyeUz8x3Jdhc.br.js'},
{'A:rms:answers:OrgId:AccountLink':'https://r.bing.com/rp/zL4sntecq0RmP6dobtS9Rd5WRvU.br.js'},
//{'A:7':7},
{'A:rms:answers:Rewards:RewardsNcHeaderBootstrap':'https://r.bing.com/rp/psgXZvzYJMEW2ydikIk493Va1d4.br.js'},
{'A:RewardsReportActivity':'https://r.bing.com/rs/6r/x2/nj/nt6a1ZR520utsLoZmSYgwxdOPgI.js?or=w'},
{'A:rms:answers:Rewards:RewardsCreditRefresh':'https://r.bing.com/rp/5L3iD467J3iJWEPwIjxlK0MMDpY.br.js'},
{'A:rms:answers:Rewards:ModernReportActivity':'https://r.bing.com/rp/9Z2GyyGvsKSVNrmOMrTfcv8z_yQ.br.js'},
{'A:rms:answers:Rewards:ReportActivityBootstrap':'https://r.bing.com/rp/K_V1CARn2Q2lTs5njJKUvUkHyi4.br.js'},
{'A:rms:answers:Identity:MobileIconScript':'https://r.bing.com/rp/dUzSc2TJEdHviToK914Fg1aekPA.br.js'},
{'A:rms:answers:VisualSystem:ScopeBarAppShortcuts':'https://r.bing.com/rp/8LIV7VPMYjV_ya4Ggnu8LBWQIQQ.br.js'},
{'A:rms:answers:VisualSystem:NotebookScope':'https://r.bing.com/rp/910ptS3pcIDQ7a5acMaHuQliuN0.br.js'},
{'A:rms:answers:VisualSystem:EnableStopLinkBehavior':'https://r.bing.com/rp/JTnIefOMiNK7DX11D7RY8i0_PKc.br.js'},
{'A:rms:answers:VisualSystem:WebScopeInteractions':'https://r.bing.com/rp/_Bf8WbhrPNleVJdfG-L0A8nld9c.br.js'},
{'A:rms:answers:VisualSystem:ScopeBarRankInst':'https://r.bing.com/rp/NfTD8Ovh04Y_Ni14YxqYB8R_2_Q.br.js'},
//{'A:8':8},
{'A:rms:answers:VisualSystem:LogTabCount':'https://r.bing.com/rp/fRSNKQanUHk53F1a1Bi8UA71Qt4.br.js'},
{'A:rms:answers:SharedStaticAssets:EsModuleShim':'https://r.bing.com/rp/DWZSY9SRnkHaYWjJ109REMim90A.br.js'},
{'A:rms:answers:Web:UetTag':'https://r.bing.com/rp/mOy7YpeLJ3c40BBAFNUI6SmOUTY.br.js'},
{'A:rms:answers:Web:UpdateDefaults':'https://r.bing.com/rp/6mZmj1db42G_jniFgdT7MCvBgyA.br.js'},
{'A:ShareWebResults':'https://r.bing.com/rs/6r/kQ/jnc,nj/P2A3uGO2O64dixlm8-ndJ5_iyo4.js?or=w'},
{'A:rms:answers:Web:KeyPressScroll':'https://r.bing.com/rp/iY8PAEydb3lbGfuJiuA9ICzXgY8.br.js'},
{'A:rms:answers:Web:AlgoTitleColorOnMousedown':'https://r.bing.com/rp/UftfQbYuKvGGEUHPU3QGHYd90Z8.br.js'},
{'A:rms:answers:Web:CursorProgressOnClick_Rebind':'https://r.bing.com/rp/yZjAz6-B4hIBhJ6D3nAyY_Ebn44.br.js'},
{'A:rms:answers:Web:CursorProgressOnClick':'https://r.bing.com/rp/zlfm-hC70pZAs62UVTTl3KShKOE.br.js'},
{'A:rms:answers:SharedStaticAssets:azure_msal_browser':'https://r.bing.com/rp/9uYIRoQB-ThMq970XKGeKvrMhL0.br.js'},
{'A:rms:answers:SharedStaticAssets:microsoft-graph-client':'https://r.bing.com/rp/bdiAPlmUnJhdap3y8myDMEGlF4w.br.js'},
//{'A:9':9},
{'A:rms:answers:Web:FreeSydneyHelper':'https://r.bing.com/rp/N0wERQqY_QwLTAsANmATXtL5fZE.br.js'},
{'A:rms:answers:Web:SydneyFSCHelper':'https://r.bing.com/rp/p8iFKqjtfmUOj6mXSomSpfpbevc.br.js'},
{'A:rms:answers:Shared:BingCore.AppendHTMLAfterOnLoad':'https://r.bing.com/rp/2LhASpM_B45Dkt22jdRkKWDJqnA.br.js'},
{'A:rms:answers:Web:SydneyExternalSerpResources':'https://r.bing.com/rp/2RCeK0DXIqmSD7PaRpZ6xLy-dAQ.br.js'},
//{'A:10':10},
{'A:rms:answers:Shared:Base64Encoder':'https://r.bing.com/rp/5FbVcVko_TuW5Y8VB4_bHoFuDm8.br.js'},
{'A:rms:answers:Shared:GlobalActionMenuV2WrapperSharing_AfterOnLoad':'https://r.bing.com/rp/FATdvfhSB-vJrkLn-dkWzqdRSDU.br.js'},
{'A:rms:answers:Shared:GlobalActionMenuV2WrapperTrigger':'https://r.bing.com/rp/EmbwE8rah_7zdUQkosWSw-5nAPY.br.js'},
{'A:rms:answers:Shared:GlobalActionMenuV2Wrapper_AfterOnLoad':'https://r.bing.com/rp/e5L7vKbubPSU1bqZ4-OGMj8wr3o.br.js'},
{'A:rms:answers:Web:SydneyFullScreenConvLogging':'https://r.bing.com/rp/44Hadr7BiNLQdKT4SHan0JHPRgc.br.js'},
{'A:rms:answers:Web:SydneyWaitlistUpdate':'https://r.bing.com/rp/X-RU3l-2R4Eoz9TUYWyziyccOjA.br.js'},
{'A:rms:answers:VisualSystem:ConversationScope':'https://r.bing.com/rp/evAU7lx8mebBaN9xocvZx8NVZhE.br.js'},
{'A:rms:answers:CodexBundle:cib-bundle':'https://r.bing.com/rp/cyU_OCO3RbZ2qeKuF-N208x6HCE.br.js'},{'A:rms:answers:SharedStaticAssets:speech-sdk':'https://r.bing.com/rp/5RUBu5dEYIDzWQtuZRVAHjBjuyc.br.js'},
{'A:rms:answers:Web:ChatHomeScreenBase':'https://r.bing.com/rp/-rTLoTob7E0ltIUEW9nZQHmVMYk.br.js'},
{'A:rms:answers:Web:ChatHomeScreen':'https://r.bing.com/rp/iKLEB3hIDCT4236vCJrv0iHxANU.br.js'},
{'A:rms:answers:Web:SydneyWelcomeScreenBase':'https://r.bing.com/rp/J1Qt_5kw_tmsXwaKeAFz2xPNi4s.br.js'},
{'A:rms:answers:Web:GPTHomeScreen':'https://r.bing.com/rp/CsCzqXab54vz3c10eLzjdO0EiqM.br.js'},
{'A:rms:answers:Web:SydneyFullScreenConv':'https://r.bing.com/rp/0UCEcxL4L_MIx61KSqZ5vt5H4V0.br.js'},
{'A:rms:answers:Notifications:BnpPartner':'https://r.bing.com/rp/LDPtmbi_w4y1oa90D_hi6HqB1QI.br.js'},
//{'A:11':11},
{'A:rms:answers:Web:SydneyConvModeBackfacePatch':'https://r.bing.com/rp/wkWt7BtQdqUJkCPKQdJdk548UFA.br.js'},
//{'A:12':12},
{'A:rms:answers:Web:SydFullScreenConvResourcesPostLoad':'https://r.bing.com/rp/Jnh8f1BaqA6QhGEDPml3FtXpFbY.br.js'},
{'A:rms:answers:SegmentFilters:DropDown':'https://r.bing.com/rp/WwTHOlBv_iLBpZXNWkp-HzVHgrM.br.js'},
//{'A:13':13},
{'A:rms:answers:Web:DnsExperimentA':'https://r.bing.com/rp/CcMXS8Oo0OUnUE0LzYK9AFJ6la8.br.js'},
{'A:rms:answers:WebResult:ExtendIconClickTargets':'https://r.bing.com/rp/R5OIlHZUEYWuNhJa46yx5Wir2pM.br.js'},
{'A:rms:answers:WebResult:CaptionClickable':'https://r.bing.com/rp/-gqBS9VzaGQOAafzweDVcqAD18I.br.js'},
{'A:rms:answers:Shared:Swipe':'https://r.bing.com/rp/3s0czFTJyV5b3KCC7geWICWvvPs.br.js'},
{'A:rms:answers:Shared:Orientation':'https://r.bing.com/rp/wNhUjm3kl_kvyfrio44J6j1zdYo.br.js'},
{'A:rms:answers:Shared:TabControl':'https://r.bing.com/rp/lwQThTlaI10v50gbypuOTf2JDcM.br.js'},
//{'A:14':14},
{'A:rms:answers:Shared:InfoBubble':'https://r.bing.com/rp/cXhWvHAhnTbr0lPlUZIG8zGWEBo.br.js'},
//{'A:15':15},
{'A:rms:answers:News:NewsAnswerHoverEffect':'https://r.bing.com/rp/BMHcFIy-Zeu4GqfEnHOyABd5ZQc.br.js'},
{'A:ProgressiveImages':'https://r.bing.com/rs/6r/sQ/jnc,nj/2RFgnacsz6nPw9vvxd8AGFyaQr8.js?or=w'},
{'A:rms:answers:News:NewsAnswerBigLogoScroll':'https://r.bing.com/rp/uq6jewoGavoU4pK6nYtO9pAum4o.br.js'},
{'A:rms:answers:Shared:Pager':'https://r.bing.com/rp/RvRBoZ5KQDNHwbHfo-_ZBZIoYQo.br.js'},
{'A:rms:answers:Shared:Chevrons':'https://r.bing.com/rp/bzAVZoOHiaJeSbLoUcTPF4HPvJQ.br.js'},
{'A:rms:answers:Shared:SlideExperienceLite':'https://r.bing.com/rp/8pMSnHJ05nB8bncpcC8ILnrRLFM.br.js'},
{'A:rms:answers:WebResult:CaptionImageOverlay':'https://r.bing.com/rp/B-tRIg18CBKTY5_L9A8pOhYyyQo.br.js'},
//{'A:16':16},
{'A:rms:answers:Multimedia:IFrameOverlayContainer_PostLoad':'https://r.bing.com/rp/mRnHl5xOMNMCkNGN3wISIz0ETug.br.js'},
{'A:rms:answers:Multimedia:ImageDetailIFrameOverlay_PostLoad':'https://r.bing.com/rp/X9zPQVZQzKFTYze2B2WNn1LJCS4.br.js'},
{'A:rms:answers:Multimedia:InsightsOverlayContainer_PostLoad':'https://r.bing.com/rp/1u_LY-3P7BIagPGDkiUCRzkKi-0.br.js'},
//{'A:17':17},
{'A:rms:answers:Multimedia:VideoSerpAnswer':'https://r.bing.com/rp/8aj_I6fSAQ2HauP0CPPAfDwa2j8.br.js'},
//{'A:18':18},
{'A:rms:answers:MultimediaComponents:VideoTileVisualComponent':'https://r.bing.com/rp/LTCT2zdUcB3ayDDUpC7BI5zxXuE.br.js'},
//{'A:19':19},
{'A:rms:answers:Multimedia:MMUtilsDefinition':'https://r.bing.com/rp/HdiojNH85n4iu87NAQvDH5bKMnM.br.js'},
{'A:rms:answers:Multimedia:MMUtilsStyle':'https://r.bing.com/rp/s_KB_GYETp6JptI_mOoLcYDN4OY.br.js'},
{'A:rms:answers:MultimediaComponents:VideoRichHoverUtils':'https://r.bing.com/rp/hSAjq6w-jLSduDuFCKOr-TOJIA4.br.js'},
{'A:rms:answers:Multimedia:MMUtilsEvent':'https://r.bing.com/rp/WPedHfV8dQrn4qkif5azDZSqmn8.br.js'},
{'A:rms:answers:MultimediaComponents:VideoRichHoverEnumsAndConstants':'https://r.bing.com/rp/ARkHhpPGNjemsh-1_dUh9nylFLg.br.js'},
{'A:rms:answers:MultimediaComponents:ThumbnailPlayerOverlayComponent':'https://r.bing.com/rp/5jOFZTRZRQNYEniUpjuVlRlTSUA.br.js'},
{'A:rms:answers:MultimediaComponents:Html5VideoSmtPlayer':'https://r.bing.com/rp/8BLbyUK5EaqCuzmCEcf9-meevmE.br.js'},
{'A:rms:answers:MultimediaComponents:VolumeIconWithSliderBar':'https://r.bing.com/rp/YOfvioAlqeLJzUxJ3VRDJvFPi5Q.br.js'},
{'A:rms:answers:Multimedia:MMUtilsQueryAndUrl':'https://r.bing.com/rp/7LkHIwasTuL6tufzeF3vEaazAxw.br.js'},
{'A:rms:answers:MultimediaComponents:ThumbnailUrlConsts':'https://r.bing.com/rp/MCwdqGFTwqu20jt3177s57V4wZk.br.js'},
{'A:rms:answers:Multimedia:THUrlGenerator':'https://r.bing.com/rp/dDiRViGCXHkOBl6zHkdBDLk0yFg.br.js'},
{'A:rms:answers:MultimediaComponents:ThumbnailPlayerComponent':'https://r.bing.com/rp/WvsAjDpxGd1ajigH6cH78uvLzBI.br.js'},
{'A:rms:answers:MultimediaComponents:VideoRichHoverInstrumentation':'https://r.bing.com/rp/qY42f0yZJzcOD6Gr6zubromZGRk.br.js'},
{'A:rms:answers:MultimediaComponents:VideoRichHoverBundle':'https://r.bing.com/rp/g7NRXrmIjF1z4aM0YyGzJ3H8Tsc.br.js'},
//{'A:20':20},
{'A:rms:answers:Shared:AjaxDataLoader':'https://r.bing.com/rp/wJ4ypLxMemRfvxvJkUCpuYEBwew.br.js'},
{'A:rms:answers:Shared:SlideExperience':'https://r.bing.com/rp/gfI083AUtzdZuPReAN6CvS-Ca98.br.js'},
{'A:rms:answers:RelatedQnA:VideoAnswerCard':'https://r.bing.com/rp/b1KIElS8CoqVTHRuF5IaPe1_xYo.br.js'},
//{'A:21':21},
{'A:rms:answers:Shared:LGWidget':'https://r.bing.com/rp/RMRjctrz--TNvbEliu0umBztyAQ.br.js'},
{'A:rms:answers:QuerySuggestion:ClickBackRS':'https://r.bing.com/rp/jJ4Nh5QSrSxNeZCoXz6QBAA-1pM.br.js'},
//{'A:22':22},
{'A:rms:answers:WPC:EntityPanePreview':'https://r.bing.com/rp/ArHyxbBQcE8YU5aazNfFDRsXU7E.br.js'},
//{'A:23':23},
{'A:rms:answers:Shared:ResponsiveImageResize':'https://r.bing.com/rp/RoFJpzeql5F0UwlxxhHctrDb1gI.br.js'},
{'A:rms:answers:SportsV2:LiteExpandableFacts':'https://r.bing.com/rp/EUVdjTinS37NjfSnARYo0K9VebI.br.js'},
{'A:rms:answers:Shared:ExpandableInlineContainer':'https://r.bing.com/rp/63qjYW4S9DHDGHceAP26U3WNhl0.br.js'},
{'A:rms:answers:Shared:ExpansionWrapper':'https://r.bing.com/rp/fWL2xzriHzWjhZXNxQ8Rm3CwUUU.br.js'},
{'A:rms:answers:Shared:ThumbsUpDownFeedback':'https://r.bing.com/rp/64ZSq206R4R8FyO8Y2Q8OdNSmMs.br.js'},
//{'A:24':24},
{'A:rms:answers:VisualSystem:LargerClickTarget':'https://r.bing.com/rp/4a2l6ts7ENpX5gGW0kp5U2iD6h8.br.js'},
{'A:rms:answers:VisualSystem:IPv6Test':'https://r.bing.com/rp/eKvcHdnNwo1WcxoSioV4ztnfZk8.br.js'},
//{'A:25':25},
{'A:rms:answers:Web:SerpKeyboardNavigation_Selector':'https://r.bing.com/rp/Sv8bO2oxkbGjZh6Pe_GKzG1DtDU.br.js'},
{'A:rms:answers:Web:SerpKeyboardNavigation':'https://r.bing.com/rp/-2EVJNDwymhr08bVch00GwpjiDA.br.js'}
//{'A:26':26}
);
